dist: bionic

language: go

go:
- 1.12.x

before_install:
  - sudo apt-get install -y spin

install:
- go get -u golang.org/x/lint/golint

script:
- go vet ./...
- if [ "$( gofmt -l . )" ]; then gofmt -d; exit 1; fi
- golint -set_exit_status ./...
- go test ./...
- cd spin; ./run.sh

notifications:
  email: false

